### PR TITLE
Adding my name to the mix

### PR DESCRIPTION
**Pull request by heathermeeker**
## Self assessment:

Please fill out the following self assessment and provide context:

- [x] (1 pt/year, 3 pts max) active participation in a well-known legal
discussion group
- [x] (1 pt) hold a law degree from a recognized university
- [x] (2 pt/publication, 2 pts max) publish an intermediate to advanced article
about legal issues relevant to this list
- [ ] (1 pt/referral, 2 pts max) receive a recommendation from someone on this
list
- [ ] (1 pt) demonstrate basic proficiency using the `git` tool
- [ ] (2 pts) demonstrate basic proficiency using the `gpg` tool with email

### CODE REVIEW

**Comment by purpleidea** [comment]
Hi @heathermeeker !

Thank you for your patch. The commit failed because we added some tests to keep things more consistent. You will need to rephrase your commit message with a prefix, like:

`individuals: Adding my name to the mix`

To do this you can `git commit --amend` (now add the prefix) and then force push to this branch. In my case that would be: `git push origin whatever-you-named-the-branch`

At the same time you might also want to consider adding a file in the `individuals/` folder. Look at the other examples. If you do, then add it with `git add` and it will get added to the commit when you do the above `git commit --amend`.

Lastly, the entry needs to be in alphabetical order for the test to pass. So please move your name up one, and `git add individuals.md` as well.

Thanks!
James

PS: I added the instructions since I'm not familiar with your git expertise level, but happy to answer questions if you've got them.

**Comment by heathermeeker** [comment]
The assessment seems self-referential.  I can't "self-assess" a referral.  And I thought the action of creating the pull request was the demonstration of proficiency, which can't be self-assessed prior to doing it.

**Comment by purpleidea** [comment]
@heathermeeker I'm not sure what you're referring to, but you just have some small fixes to do, nothing to do with self assessment. If I missed something, let me know. Thanks!

**Comment by purpleidea** [comment]
@heathermeeker Hiya, would you like to fixup this patch and resubmit or should I close?

Thanks!

**Comment by heathermeeker** [comment]
Go ahead and close. I actually use GITHUB pretty regularly but I still can't figure out what you are asking for here.

**Comment by purpleidea** [comment]
@heathermeeker 

> Go ahead and close. I actually use GITHUB pretty regularly but I still can't figure out what you are asking for here.

We were asking you to edit your commit since it didn't pass the automated tests. To run them you can run `make test` and see what the errors are. I also described the necessary changes for you in https://github.com/purpleidea/legal-hackers/pull/8#issuecomment-447615770

I'll close, but if you'd like to re-open, or want some help editing your commit, let me know and I'm happy to help you with git!

Thanks!

**Pull request closed without merging**
