### PR TITLE
individuals: Add Carlo

### PR DESCRIPTION
**Pull request by kappapiana**
Ok, this time it should definitely be correct. I have create a separate branch for this patch and another for another patch. I promise I won't touch it any more ;-)

### CODE REVIEW

**Review by purpleidea — COMMENTED** [review]
This looks perfect *except* you have added the .PULL_REQUEST_TEMPLATE into this same commit. Let's save that for a separate commit. You could split that into a separate commit inside this same pull request, but that's more advanced. For now, let's keep it to one commit to each pull request. Please remove that and send away =D

**Comment by purpleidea** [comment]
Btw, sorry for my delay in responding, I was quite sick up until today.

**Comment by kappapiana** [comment]
no problem. 

Digging deeper I've seen my mistake, I've created a new branch but did not have time to issue a separate pull request. 

It's kinda fun. ;-)

Carlo

**Comment by purpleidea** [comment]
@kappapiana So, since this is all work we're reviewing *before* it gets pushed to git master, we can change anything we like to make it look "perfect". IOW we hide our mistakes, but we still want to "show our work". Once things are in git master, they're basically permanent. (By convention.) So as a result, you should not have the "Delete .PULL_REQUEST_TEMPLATE" be a separate commit. It should just be one commit that never had that. Make sense?

**Comment by purpleidea** [comment]
(Btw the "show our work" was alluding to the fact that in general, complex patches should be split into multiple commits to show the logical flow of the work, and separate each independent item.)

**Comment by kappapiana** [comment]
> @kappapiana So, since this is all work we're reviewing _before_ it gets pushed to git master, we can change anything we like to make it look "perfect". IOW we hide our mistakes, but we still want to "show our work". Once things are in git master, they're basically permanent. (By convention.) So as a result, you should not have the "Delete .PULL_REQUEST_TEMPLATE" be a separate commit. It should just be one commit that never had that. Make sense?

Sort of ;-)

**Comment by purpleidea** [comment]
> Sort of ;-)

In GH you'll see you add a second commit. Instead, what you should have done was after you deleted the .PULL... file, you should have done `git commit --amend` to make that change part of the earlier commit adding your name, instead of doing a NEW commit with `git commit`.

**Comment by purpleidea** [comment]
\o/ merged! woo! thanks =D

**Pull request merged**
